### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by natew** [reapp/reapp-ui#10]
Need a much better system for documenting components. They are changing really fast, so this is important. Ideally it's all automated and extracted from the code. I'd like to see:
- JSDoc above each component
- PropTypes with comments that explain each one

Finally, a script in [github.reapp.io](https://github.com/reapp/github.reapp.io) that automatically grabs these and places them on the site.

Final step would be to do something like what @gaearon has talked about, having automatic demos that can be displayed on the site next to them, with realtime editable props.

**Comment by callum** [comment]
Whilst we're lacking in documentation where is a good place for support? I'm looking to implement a `NestedViewList` with routing. E.g. **/user** -> **/user/1** -> **/user/1/details** with back buttons in the titlebar.

**Comment by natew** [comment]
Yep, this is working. Check out our example repos:

https://github.com/reapp/hacker-news-app
https://github.com/reapp/kitchen-sink

They both use the RoutedViewListMixin which helps with that.

**Comment by natew** [comment]
Once we get a good amount of these tickets opened, I'll start a gitter for live support.
