### ISSUE TITLE
public key denied?

### ISSUE THREAD

**Issue by oconnoat** [reapp/reapp-ui#2]
When I run reapp new:

Creating new reapp folder for: example...
Running git clone --depth=1 git@github.com:reapp/reapp-starter.git /home/vagrant/example...

 Error
{ [Error: Command failed: Cloning into '/home/vagrant/example'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
] killed: false, code: 128, signal: null }

**Comment by natew** [comment]
Make sure you have github's publickey setup:

https://help.github.com/articles/error-permission-denied-publickey/

**Comment by oconnoat** [comment]
Thanks!
