### ISSUE TITLE
How to preview during development?

### ISSUE THREAD

**Issue by nolimits4web** [reapp/reapp-ui#23]
Sorry for lot of probably stupid questions :) 
But i am still can't really understand UI developing workflow, i know where i need to do changes to contribute, but how can i preview/see them? Or is it supposed to also have running Kitchen Sink, but in this case i need to make changes there and then copy it here? Anyway, how do you do that? :relaxed:

**Comment by natew** [comment]
No worries! This is something I should've done sooner. I've added a contributing section to the readme that should help with this:

https://github.com/reapp/reapp-ui#contributing

**Comment by natew** [comment]
Let me know if you have any more questions

**Comment by nolimits4web** [comment]
Yep, that what i was looking for, thanks! :+1:
