### ISSUE TITLE
Modals don't prevent tapping lower elements

### ISSUE THREAD

**Issue by appsforartists** [reapp/reapp-ui#3]
On the [Button demo](http://kitchen.reapp.io/buttons), notice the bounding box of the bug blue button in the middle.  Tap any button to pull up the modal, then tap **OK** within the confines of the big blue button.  the **OK** will close the modal, but the big blue button will trigger a new one, both reacting to a single event.

**Comment by natew** [comment]
Should be fixed, thanks!
