### ISSUE TITLE
Cannot read property 'styles' of undefined

### ISSUE THREAD

**Issue by lazywei** [reapp/reapp-ui#44]
This commit https://github.com/reapp/reapp-ui/commit/61b1e38ba1360ef13b14151245de8387eef0984f#diff-1c94f8f2d2fe2dfa1fbf225cc13ac874R18 seems to introduce the bug. The `context.theme` might be undefined.

**Comment by natew** [comment]
Could you give me the error message where this is happening?

**Comment by natew** [comment]
Be sure to use the `<Theme>` helper when you upgrade your apps to 0.8, I'm going to add documentation to it today but the Kitchen/HN demo and new starter repo has it.

**Comment by natew** [comment]
This should be fixed if you're using <Theme> or the new reapp-kit helpers. Let me know if not.
