### ISSUE TITLE
Home page demo is broken for me ( chrome + mac )

### ISSUE THREAD

**Issue by neerajsingh0101** [reapp/reapp-ui#45]
- Mac version. http://take.ms/uFLQZ
- Chrome version. http://take.ms/Qww3V
- Viideo of the bug . https://vimeo.com/123206130

**Comment by natew** [comment]
Final question I'd have is to run it in a private browsing session so you don't have any plugins enabled just in case one of those is messing with it (unlikely).

Another would be to right click when it isn't working and "Inspect Element..." and see what it inspects.

**Comment by neerajsingh0101** [comment]
I made another video answering your question.

https://vimeo.com/123210122

**Comment by natew** [comment]
It says the video is private for me

**Comment by neerajsingh0101** [comment]
Sorry about that. It's public now.

**Comment by neerajsingh0101** [comment]
I restarted chrome for a different reason and now the demo is working. Very weird. I think that was a one-off case and this issue can be closed now.

**Comment by natew** [comment]
Glad to hear. I got some weird chrome stuff sometimes too. Oh well. Thanks for the report.
