### ISSUE TITLE
Can't style Card title or content if it contains just the digit 0.

### ISSUE THREAD

**Issue by mbrookes** [reapp/reapp-ui#47]
Here's an obscure one! 

If the text of a Card is (just) the digit zero (for example using it to display a counter starting at 0), styles from `styles: { title: {} }` and `styles: { content: {} }` don't get applied. Any other single or multiple digits are fine.

This only applies if the title or content are supplied through a variable such as `props`. The workaround is to call `.toString()` on the variable:

``` javascript
getInitialState() {
    return {
        title: 0
        content: 0
    };
},
render() {
    return (
        <Card title={this.props.title.toString()} {...cardProps}>
            {this.propscontent.toString()}
        </Card>
    );
}
```

**Comment by natew** [comment]
The Title prop is meant to be a string only, so this makes sense actually. Appreciate the report but there should be a warning if you don't use a string, so going to close this.

**Comment by mbrookes** [comment]
Yeah, I see that now, although the DRY fanatic in me wants `title.toString()` or `"" + title` to be upstream in reapp rather than in the users code. :smile:

**Comment by natew** [comment]
I'd accept a PR for that if you submit one.

**Comment by mbrookes** [comment]
Hmm, no you're right, can't be done as propType will throw a warning before we can intervene to coerce the number to a string. It's not a big deal, just thought it was wacky that only a 0 loses its styling...

**Comment by natew** [comment]
You can do:

```
React.PropTypes.oneOfType([ React.PropTypes.string, ... ])
```

At this point I could have just added it haha :)

**Comment by mbrookes** [comment]
Guess I needed to RTFM some more! :)
