### ISSUE TITLE
There is an issue when 'reapp run' is running

### ISSUE THREAD

**Issue by rkmax** [reapp/reapp-ui#50]
On rebuild the app for some reason the `this.styles` is not defined, even if i edit the code for avoid the undefined i get other errores. I like the app lose the context when the app is running

**Comment by natew** [comment]
I get this too. It seems like hot-loading somehow loses context briefly. Going to ping creator of react-hot-loader on this, @gaearon any ideas?

**Comment by gaearon** [comment]
Pretty sure it's https://github.com/facebook/react/issues/3404 (fixed in https://github.com/facebook/react/pull/3494).
This should get into 0.13.2: https://github.com/facebook/react/issues/3629.

**Comment by gaearon** [comment]
This [should be out](http://facebook.github.io/react/blog/2015/04/18/react-v0.13.2.html) in 0.13.2.

**Comment by natew** [comment]
Cool, thanks Dan.
