### ISSUE TITLE
How to require as a standalone library ?

### ISSUE THREAD

**Issue by jide** [reapp/reapp-ui#51]
If I follow the examples : 

```
import Theme from 'reapp-ui/helpers/Theme';
```

This won't work, since the files are in `src`. Requiring from `src` won't do it with browserify since files are not compiled in `src`.

Anything I'm missing here ?

**Comment by natew** [comment]
I made a mistake when I moved to a new build system. The new version of reapp-ui should fix this.

**Comment by jide** [comment]
Ah ok then. Any idea when this new version would be released ? Which version may I downgrade to to test in the meantime ?

**Comment by natew** [comment]
It's released! Sorry that wasn't clear.

**Comment by jide** [comment]
Oh ok, great then :)

But if I use the 0.12.37 (is that the lastest release you're talking about ?) version and I do : 

```
import Theme from 'reapp-ui/helpers/Theme';
```

I get : 

```
Error: Cannot find module 'reapp-ui/helpers/Theme'
```

**Comment by natew** [comment]
Latest version is 0.12.38

**Comment by jide** [comment]
That was close ! Thank you for your help, it works now.
