### ISSUE TITLE
How to use as a standalone library ?

### ISSUE THREAD

**Issue by jide** [reapp/reapp-ui#52]
I'm having hard time understanding how reapp-ui whould be used on its own. I know documentation is still in progress but I could not figure how to get started.

What am I missing ?

theme.js : 

``` es6
let theme = {
  constants: {},

  styles: {
    SomeCustomComponent: {
      self: {
        width: 200
      }
    }
  },

  animations: {}
};

export default theme;
```

App.jsx : 

``` jsx
import BlankTheme from '../../themes/blank/theme';
import Theme from 'reapp-ui/helpers/Theme';

let App = React.createClass({
    render() {
        return(
            <Theme { ...BlankTheme }>
                <SomeCustomComponent />
                <AnotherComponent>
                    <AChildComponent />
                </AnotherComponent>
            </Theme>
        );
    }
});
```

**Comment by natew** [comment]
Here's how you could create a theme, as demod by the kitchen sink app:

https://github.com/reapp/reapp-ui/blob/master/src/themes/ios/theme.js

**Comment by natew** [comment]
If you want to add custom themes to that, you'd do it like so:

https://github.com/reapp/hacker-news-app/blob/451449c1b580e5a12ce3a86ab1b3e3778045be32/app/theme/index.js

The repo from that commit has all the stuff you'd need including loading custom component styles. Though if you're doing custom components, I'd recommend just having the styles in the same file and managing them yourselves. The theme stuff is only for re-styling components in the UI.

**Comment by jide** [comment]
Yes I did look at these examples, but a barebone example would really help to understand the base logic.

I'm trying to make a themable set of components that could be easily overridable.

If I understand correctly, the role of `UI` is to facilitate the merging of multiple styles / constants / animations into one object, am I right ?

Reduced to its minimum, would this be correct to create a theme ?

``` es6
import UI from 'reapp-ui';

UI.addStyles(
  {
    List: {
      self: {
        background: '#eee'
      }
    }
  }
);

export default UI.getTheme();
```

Thanks for your help !

**Comment by natew** [comment]
Yep that's pretty much it. Check out the logic in index.js to load them, and also in mixins/Styled.js to see some of the syntax that goes into helping them.

Are you looking to make new components? What's your more specific case? Could be good to know so I could make it easier for someone like you to develop with.

**Comment by jide** [comment]
Thanks for the leads, I'll look into this.

We have an existing app with custom styles that fit one particular design, and we want to make this a generic, customizable product. So reapp-ui sounds useful in our case.
