### ISSUE TITLE
Use Radium?

### ISSUE THREAD

**Issue by mbrookes** [reapp/reapp-ui#56]
This looks like a really good fit with reapp:

http://formidablelabs.com/blog/2015/03/01/launching-radium/
http://projects.formidablelabs.com/radium/

**Comment by natew** [comment]
I think it is cool, but we are close to having most of it's features supported, in what I think will be a simpler and more standard syntax. But it is an option and if someone submitted a PR showing how it would improve Reapp I'd be open to accepting it.

**Comment by jide** [comment]
Radium does not support converting inline style to real css stylesheets.

**Comment by natew** [comment]
Added radium for now as react-style is fairly outdated.

**Comment by mbrookes** [comment]
Welcome back! :)
