### ISSUE TITLE
this._processChildContext is not a function

### ISSUE THREAD

**Issue by 3dd13** [reapp/reapp-ui#59]
when I reapp run, there is an error in web console

```
this._processChildContext is not a function
```

after checking the code in facebook/react, the method is not defined in 13.3, but available in 14.0-alpha.

and from the react issue list, the method will be gone in the master after merging the commit too: https://github.com/facebook/react/pull/3711

I am using reapp-kit 1.2.14 and react is on 13.3

**Comment by ganmor** [comment]
The current version of contextPatch does not work if React > 0.13.1

**Comment by natew** [comment]
Hm, this is not good. I can put stricter deps on 0.13.1 for now. Any other ideas?

**Comment by 3dd13** [comment]
I haven't read the code and commit log

The reason of having this context patch, is it still a valid reason now
with latest react ?

If yes, can make a new context patch with latest react mount/unmount
component
If no, just remove this patch.

**Comment by davidgruebl** [comment]
Ran into the same issue yesterday, I temporarily fixed this as suggested by strictly depending 0.13.1. I'd suggest to also apply this for now to the starter-default repo so scaffolding new apps works: https://github.com/reapp/starter-default/pull/1

**Comment by natew** [comment]
0.14 updates in new version (though not fully working, would love help).
