### ISSUE TITLE
requireFunc is not defined

### ISSUE THREAD

**Issue by frederickfogerty** [reapp/reapp-ui#66]
https://github.com/reapp/reapp-ui/blob/master/src/index.js#L94

Just re-downloaded my `node_modules` directory, and I'm getting this error.

**Comment by yornaath** [comment]
I am getting this to. I am not using reapp kit. I am using standalone reapp-ui and reapp-routes

**Comment by frederickfogerty** [comment]
Yeah, I stopped using reapp based on the lack of anything - support or development.

**Comment by natew** [comment]
This one is fixed but there are others that need love. Added you both as contributors! Help always appreciated.
