### ISSUE TITLE
Minor style bug: left border incorrectly showing on alert OK button

### ISSUE THREAD

**Issue by adamschwartz** [reapp/reapp-ui#7]
![screen shot 2015-02-10 at 1 43 03 pm](https://cloud.githubusercontent.com/assets/154613/6133821/afd3f5f6-b12a-11e4-8f2b-836bf756dfbb.png)

![screen shot 2015-02-10 at 1 45 09 pm](https://cloud.githubusercontent.com/assets/154613/6133835/c51dc900-b12a-11e4-8adc-020b9266290c.png)

**Comment by adamschwartz** [comment]
Looks adding `borderLeft: "none"` to https://github.com/reapp/reapp-ui/blob/master/themes/ios/styles/ModalButton.js would resolve the issue, although that may be needed for multiple button support? In that case maybe you can apply it only to `:first-child` somehow.

**Comment by natew** [comment]
Yep, thank you. We actually had firstChild but in a very recent change we've broken it. We moved modals to use ButtonGroup, which typically actually did the "reverse", so we just need to make ModalButtonGroup or modify ButtonGroup to support it again.

**Comment by adamschwartz** [comment]
Cool. Yeah in left-to-right languages I generally place in-between borders/margins on the bottom and right and cancel them on last children.

**Comment by natew** [comment]
This should be fixed in 0.8.20, let me know if it works for ya.

**Comment by adamschwartz** [comment]
Looks fixed on http://kitchen.reapp.io/buttons. Thanks!
