### ISSUE TITLE
react v0.14 PeerDependencies Issue 

### ISSUE THREAD

**Issue by CarpeDN** [reapp/reapp-ui#86]
Hi,

Been trying to run the homepage commands:
npm install -g reapp
reapp new myapp

and I get the following errors. They seem to be associated with the new version of React? Can anyone please provide help? The error message is below. Thanks!

Creating new reapp folder for: myapp...
Running git clone --depth=1 https://github.com/reapp/starter-default /Users/DN/Programming/myapp...
Running git init...
Inserting your name...
Running npm install...

 Error
{ [Error: Command failed: /bin/sh -c npm install
npm WARN package.json myapp@1.0.0 No repository field.
npm WARN deprecated react-tools@0.13.2: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
WARN engine stacktrace-parser@0.1.1: wanted: {"node":"~0.10"} (current: {"node":"5.1.0","npm":"2.5.1"})
npm WARN package.json node-pre-gyp@0.6.15 No README data
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/5.1.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.1.0
npm ERR! npm  v2.5.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer omniscient@3.3.0 wants react@>=0.12.0 || >=0.14.0-alpha
npm ERR! peerinvalid Peer react-router@0.13.5 wants react@0.13.x||0.14.x
npm ERR! peerinvalid Peer reapp-routes@0.10.12 wants react@0.13.x
npm ERR! peerinvalid Peer reapp-ui@0.12.70 wants react@0.14.x

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/DN/Programming/myapp/npm-debug.log
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c npm install' }

$ node -v
v5.1.0

$ npm -v
2.5.1

**Comment by iansinnott** [comment]
I'm surprised no one has responded to this in a month. It's absolutely a breaking issue. As @CarpeDN pointed out, the reproduction steps are quite simple:

```
npm install -g reapp
reapp new myapp
```

**Comment by natew** [comment]
It's open for any help. If you submit a PR I will accept immediately, I don't have time to fix on my own.

**Comment by alvimm** [comment]
I had the same problem.

My npm version was 2.4.x. I installed the last version (3.5.3) with `npm install -g npm` and it worked.
Hope it helps.

**Comment by whobutsb** [comment]
Bump. I'm having some issues creating a new app as well.  Any work arounds for this?

**Comment by paskuale75** [comment]
yet it seems so simple to install but it is full of poorly documented exceptions, is making me lose desire to keep working (Ubuntu). thanks

**Comment by ryd0rz** [comment]
## Currently working in Master. Apologies for delay.

Alex-Ms-MacBook-Pro:~ Alex.Merrifield$ reapp new myapp
Creating new reapp folder for: myapp...
Running git clone --depth=1 https://github.com/reapp/starter-default /Users/Alex.Merrifield/myapp...
Running git init...
Inserting your name...
Running npm install...
Running npm dedupe react...
Done!
Alex-Ms-MacBook-Pro:~ Alex.Merrifield$ node -v
v5.10.0
Alex-Ms-MacBook-Pro:~ Alex.Merrifield$ npm -v
3.8.3

**Comment by ryd0rz** [comment]
Please create a new ticket if you are still having issues, and I will try to help pinpoint the actual cause.
