### ISSUE TITLE
warning deprecated

### ISSUE THREAD

**Issue by jackyon** [reapp/reapp-ui#87]
hi, I just trying to use the reapp-ui with react (0.14.2)

but I got the errors:
Warning: require('react/addons') is deprecated. Access using require('react-addons-{addon}') instead.
Warning: Button.getDOMNode(...) is deprecated. Please use ReactDOM.findDOMNode(instance) instead.

here is my codes:

``` javascript
import React, { Component } from 'react'
import iOSTheme from 'reapp-ui/themes/ios/theme'
import Theme from 'reapp-ui/helpers/Theme';
import Button from 'reapp-ui/components/Button';

class Home extends Component {
    render() {
        return (
            <div>
                <Theme {...iOSTheme}>
                    <Button>test</Button>
                  </Theme>
            </div>
        )
    }
}

export default Home
```

plz advise, thx

**Comment by veeramarni** [comment]
+1

**Comment by ryd0rz** [comment]
Fixed with: https://github.com/reapp/reapp-ui/commit/0b9ccc159c4cd05f7aed015b7efeba7a9b09ceff
