### ISSUE TITLE
Version discrepancy in local reapp-ui (from repo) and npm dependency

### ISSUE THREAD

**Issue by zachswansonlud** [reapp/reapp-ui#89]
Hello,

I am working on a react 0.14.7 project using just the reapp-ui library for UI.  Wanting to make modifications (e.g. the newer version of react changes) I cloned the repo locally so that I could make changes and then depend on that in the react project.

I was able to get the integration working when installing reapp-ui via "npm install reapp-ui" but not with the local version following the directions listed in the readme.  After trying many options, I ended up doing a diff merge on the output of my react.js compiled app.js file and came across a non-syntactical difference.  In the reapp-ui version pulled from the repo, in mixins/ComponentProps.js, the "styles" property was being set by this.getStyles(ref); in the reapp-ui npm version,  the "style" property was being set by this.getStyles(ref).filter(function (x) { return !!x }).

When I made this change in my local reapp-ui project and re-built everything I was able to get it to work.  I noticed some other differences between the repo and npm but this seemed to be the one where an actual property was different.

Also, the npm package.json is showing 0.12.70 while the repo is showing 0.12.65.

Is there anyway to get the repo-version (with the ability to build, etc.) at 0.12.70 or is the only option to continue reverse engineering the differences?

Thanks,

-Zach

<img width="1137" alt="screen shot 2016-02-17 at 12 15 43 am" src="https://cloud.githubusercontent.com/assets/17028687/13116476/194ac24e-d56a-11e5-8665-62e8ae695d1f.png">

**Comment by ryd0rz** [comment]
Fixed with: https://github.com/reapp/reapp-ui/commit/b400536d55f683acbb338ab7b90f3b4ad364a7d0

Thanks, Zach!
